variables:
  os: Windows
  environment: Test

steps:
  - script: 
     echo $(variables.os)
     echo this is the first Script
    displayName: Step 1

  - script: 
     echo this the second script
    displayName: Step 2