variables:
  os: Windows
  environment: Test

steps:
  - script: 
     echo $(os)
     echo this is the first Script
    displayName: Step 1

  - script: 
     echo this the second script
    displayName: Step 2
    condition: eq(variables['environment'], 'Test')