variables:
  - group: mygroup 
  - name: scriptVar 
    value: Test 
  - name: umgebung 
    value: Test 

parameters:
  - name: environment
    displayName: 'Welche Server wollen Sie aktualisieren?'
    default: 'Dev'
    values:
      - Dev
      - Staging
      - Prod

steps:
  - script: |
     echo $(InputVar)
     echo this is the first Script
     echo Selected Environment ist ${{parameters.environment}}
     echo "##vso[task.setvariable name=InputVar;]Input was changed"
     echo "##vso[task.setvariable variable=InputVar]secretvalue"
     echo $(InputVar)
    displayName: Step 1

  - script: |
     echo this the second script $(scriptVar)
    displayName: Step 2
    condition: eq(variables['umgebung'], 'Test')

  - script: 
     echo this is the group $(status)
    displayName: Step 3 